using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CSC237_mlopezfleming_ContactManager.Models
{
    public class Contact
    {
        // primary key - generated by database
        [Key]
        public int ContactId { get; set; }
        
        [Required(ErrorMessage = "Please enter a first name.")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Please enter a last name.")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Please enter a phone number.")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Please enter a first name.")]
        public string Email { get; set; }

        public string Organization { get; set; } // Optional
        public DateTime DateAdded { get; set; } // Set by application

        // Foreign Key
        [ForeignKey("CategoryId")]
        public Category Category { get; set; }

        [Range(1, 1000000000, ErrorMessage = "Please select a category.")]
        public int CategoryId { get; set; }

        // read-only property
        public string Slug => FirstName?.Replace(' ', '-').ToLower() + '-' + LastName?.Replace(' ', '-').ToLower();
    }
}
